### ISSUE TITLE
Error 500 - Typed property App\Entity\Torrent\Torrent::$uplver must be bool, int used

### ISSUE THREAD

**Issue by slrslr** [Rhilip/RidPT#54]
YI have just created accoutn and loigged into https://ridpt.top and clicked Torrents tab ( https://ridpt.top/torrents ) and see the error 500 - "Typed property App\Entity\Torrent\Torrent::$uplver must be bool, int used"

```
TypeError Code 0

/data/wwwroot/ridpt.top/framework/ORM/Entity/AbstractModel.php Line 19

#0 /data/wwwroot/ridpt.top/application/Entity/Torrent/Torrent.php(61): Rid\ORM\Entity\AbstractModel->importAttributes()
#1 /data/wwwroot/ridpt.top/application/Entity/Torrent/TorrentRepository.php(47): App\Entity\Torrent\Torrent->__construct()
#2 [internal function]: App\Entity\Torrent\TorrentRepository->App\Entity\Torrent\{closure}()
#3 /data/wwwroot/ridpt.top/application/Entity/Torrent/TorrentRepository.php(46): array_map()
#4 /data/wwwroot/ridpt.top/application/Forms/Torrents/SearchForm.php(162): App\Entity\Torrent\TorrentRepository->getTorrentBySearch()
#5 /data/wwwroot/ridpt.top/application/Controllers/Torrents/SearchController.php(23): App\Forms\Torrents\SearchForm->flush()
#6 [internal function]: App\Controllers\Torrents\SearchController->index()
#7 /data/wwwroot/ridpt.top/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array()
#8 /data/wwwroot/ridpt.top/vendor/php-di/php-di/src/Container.php(276): Invoker\Invoker->call()
#9 /data/wwwroot/ridpt.top/framework/Http/Application.php(72): DI\Container->call()
#10 /data/wwwroot/ridpt.top/framework/Http/Application.php(77): Rid\Http\Application->runWithMiddleware()
#11 /data/wwwroot/ridpt.top/application/Middleware/AuthMiddleware.php(106): Rid\Http\Application->Rid\Http\{closure}()
#12 /data/wwwroot/ridpt.top/framework/Http/Application.php(78): App\Middleware\AuthMiddleware->handle()
#13 /data/wwwroot/ridpt.top/framework/Http/Application.php(77): Rid\Http\Application->runWithMiddleware()
#14 /data/wwwroot/ridpt.top/application/Middleware/IpBanMiddleware.php(25): Rid\Http\Application->Rid\Http\{closure}()
#15 /data/wwwroot/ridpt.top/framework/Http/Application.php(78): App\Middleware\IpBanMiddleware->handle()
#16 /data/wwwroot/ridpt.top/framework/Http/Application.php(55): Rid\Http\Application->runWithMiddleware()
#17 /data/wwwroot/ridpt.top/framework/Http/Application.php(23): Rid\Http\Application->runAction()
#18 /data/wwwroot/ridpt.top/application/Commands/Server/AbstractServerCommand.php(234): Rid\Http\Application->run()
#19 [internal function]: App\Commands\Server\AbstractServerCommand->App\Commands\Server\{closure}()
#20 /data/wwwroot/ridpt.top/application/Commands/Server/AbstractServerCommand.php(108): Swoole\Server->start()
#21 /data/wwwroot/ridpt.top/application/Commands/Server/StartCommand.php(30): App\Commands\Server\AbstractServerCommand->startServer()
#22 /data/wwwroot/ridpt.top/vendor/symfony/console/Command/Command.php(258): App\Commands\Server\StartCommand->execute()
#23 /data/wwwroot/ridpt.top/vendor/symfony/console/Application.php(911): Symfony\Component\Console\Command\Command->run()
#24 /data/wwwroot/ridpt.top/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#25 /data/wwwroot/ridpt.top/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun()
#26 /data/wwwroot/ridpt.top/bin/console(74): Symfony\Component\Console\Application->run()
#27 {main}
```

tab "Collections" and "Forums" shows error 404

**Comment by HDVinnie** [comment]
> tab "Collections" and "Forums" shows error 404

RidPT is in very early development. Features like Collections, Forums and more are not functional and you're simply just seeing placeholders one the frontend.

**Comment by Rhilip** [comment]
@HDVinnie are right, Just placeholders.
RidPT is in very early development and I'm now exhausted to build the whole swoole framework and frontend, 
And just want to switch to easyswoole (as api and tracker server) and Vue (as frontend).
Also I'm very busy at work now, so this project may stop for a while.
So this Project may stop for a while until I'm ready for commit again.
